services:
  - type: web
    name: tijeux
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: PUBLIC_ORIGIN
        sync: false
